### ISSUE TITLE
Canary Confusion

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#10]
In the attached file (after_before.spear) there is a set of assumptions to increment a real number value by some const value. In a trivial case, the assumption on the in-value made in a01b is mirrored as a requirement r_03. This passes and passes the canary requirement. Why does the a01b and a02a assumption combination eliminate possible constraint space so that the canary is proven true?

[after_before_v2.zip](https://github.com/lgwagner/SpeAR/files/219357/after_before_v2.zip)

**Comment by lgwagner** [comment]
Try checking for logical consistency using SMTInterpol (Z3's consistency check on this is not working correctly, thus I'll leave the issue open until that is resolved.

You should see something like this:

![image](https://cloud.githubusercontent.com/assets/2699181/14568042/d0521748-02fc-11e6-9cc9-2ca310807c5b.png)

**Comment by lgwagner** [comment]
This problem is also solved by using Z3 version 4.3.2. It seems bugged for the consistency check as well.
