### ISSUE TITLE
View conflicting constraints seems to be broken

### ISSUE THREAD

**Issue by jendavis** [lgwagner/SpeAR#101]
When the consistency check results in invalid, there is supposed to be a right-click option to view conflicting constraints. This is not working for me in SpeAR 2.1.0 beta (nothing appears to happen when I right-click on the invalid result). It does work in SpeAR RC 21.

**Comment by lgwagner** [comment]
Clarified with @jendavis that this is operating correctly, but that we ought to include more information to the user to make them aware that viewing conflicting constraints can only happen when IVC is enabled.
