### ISSUE TITLE
Provide Mac Product

### ISSUE THREAD

**Issue by manthonyaiello** [lgwagner/SpeAR#12]
SpeAR needs a .product file configured for build on a Mac, so that Mac users can use the tool.

**Comment by lgwagner** [comment]
Tony was this resolved on your end? If so, can you or I close it?

**Comment by manthonyaiello** [comment]
No — for reason I don’t understand, Eclipse continues to fail to generate an actual Mac executable, when I export from my product file. The thing it generates is completely broken — although I can now reorganize it a little bit and get it to actually become an executable. But that’s a manual step.

It _feels_ like an Eclipse bug, but that doesn’t make sense, as it was in Mars as well as in Neon.

**Comment by manthonyaiello** [comment]
Okay. Finally figured out how to get Eclipse Neon (at least) to generate a working Mac executable on the first go. This is verified working with commit 8883210d in branch bugfix/12_create_mac_product

1. Open `com.rockwellcollins.spear/product/distribute.mac.product` in Eclipse
2. Select "Eclipse Product explore wizard"
3. Configure the dialog as shown in the screenshot. Not especially which parts of the "Directory" should not be changed. (There is a path separator before "SpeAR.app/Contents", so you might enter: "~/Desktop/SpeAR.app/Contents", for example, to put SpeAR.app on your Desktop)
4. Click "Finish"

![11_28_16__9_19](https://cloud.githubusercontent.com/assets/806089/20671666/3e916b9e-b54c-11e6-885c-30983467e35f.png)

**Comment by lgwagner** [comment]
Leave this open or no?

**Comment by manthonyaiello** [comment]
No — I think that it can be closed now. Perhaps the comments I put should be merged into the README, so we know how to do the build, going forward? I can do that, if you like.
