### ISSUE TITLE
Generate PDF for Specifications Lists Inputs Only

### ISSUE THREAD

**Issue by cm3lliott** [lgwagner/SpeAR#16]
Currently the Generate PDF option for a .spear specification file only lists the input parameters and listing some of the other parameters will be useful (e.g. the outputs, constants, import dependencies etc).

**Comment by lgwagner** [comment]
This will not be addressed until we decide on a format for PDF output.

**Comment by lgwagner** [comment]
I'm closing this for now. We can re-open it down the road when we have defined a specific format to target.
