### ISSUE TITLE
Enumeration naming in CEX

### ISSUE THREAD

**Issue by lgwagner** [lgwagner/SpeAR#17]
Enuerations are not being remapped to their original names in counterexamples which can lead to some confusing traces. See below:

![image](https://cloud.githubusercontent.com/assets/2699181/15899091/41a48ea2-2d60-11e6-92bc-c3b47dc591f6.png)

**Comment by lgwagner** [comment]
This is particularly tricky because we need to append the specification names in front of the enumerations to ensure uniqueness when enumerations across multiple files share names. We do not attempt to do a dependency analysis, so we just pull all the type declarations in across the import chain. If two enumeration types share an enumeration value with the same ID, Jkind will crash which is sort of horrible from the user's standpoint.

**Comment by manthonyaiello** [comment]
As far as I can tell, this issue has been fixed and should be closed.

**Comment by lgwagner** [comment]
This is fixed.
