### ISSUE TITLE
Naming in Counterexamples

### ISSUE THREAD

**Issue by lgwagner** [lgwagner/SpeAR#22]
There are inconsistencies in the names found in the Counterexamples if a variable is renamed. The correct way to handle this is to use the map to translate between Lustre names and Spear names.

**Comment by manthonyaiello** [comment]
I have not seen this — is it still an issue, or has it been resolved?

**Comment by lgwagner** [comment]
I honestly cannot recall. I think I might've fixed this, but I cannot tell you for sure.

**Comment by lgwagner** [comment]
closing this as we have no evidence of it.
