### ISSUE TITLE
Feature request (Low Priority): Duplicate Ids in Different Enumeration Types

### ISSUE THREAD

**Issue by jendavis** [lgwagner/SpeAR#26]
Currently SpeAR does not allow the following because it does not allow duplicate Ids ('OFF' in this case) in different enumeration types:

Switch_State_Type is an enum {OFF, ON}
Dimmer_State_Type is an enum {OFF, LOW, MED, HIGH}

It would be nice if this were allowed, and the different instances could be disambiguated based on the type. This is low priority since it's easy enough to work around:

Switch_State_Type is an enum {OFF, ON}
Dimmer_State_Type is an enum {OFF_, LOW, MED, HIGH}

**Comment by agacek** [comment]
I expect this would be fairly difficult since you'd want to do it during Xtext's linking phase, but if you are doing it based on types then you'd want an already linked model to do type inference on. Also there would be ambiguities in things like `OFF = OFF` which is type correct for both `Switch_State_Type.OFF` and `Dimmer_State_Type.OFF`.

**Comment by manthonyaiello** [comment]
I'll "me too" this issue, but suggest that a good middle ground might be to allow Java-like disambiguation through fully specified names, e.g.:

    Switch_States is an enum {OFF, ON}
    Dimmer_States is an enum {OFF, ON}

    if switch_state equal to Switch_States.ON then

This would allow for compact enumerations while also removing any ambiguity — both for the reader and for the language.

At present, I work around this issue by doing:

    Switch_States is an enum {SWITCH_OFF, SWITCH_ON}

which, for some reason, I don't like as well as `Switch_States.ON`

**Comment by lgwagner** [comment]
This would introduce a fairly complicated aspect into the grammar: qualified names. I've been working to avoid that because it would require a complete rework of the way we handle IDs. 

It's possible, just not sure that's where we want to focus right now.
