### ISSUE TITLE
Feature request: Don't require an initial value for every instance of 'previous'

### ISSUE THREAD

**Issue by jendavis** [lgwagner/SpeAR#27]
I would like to write an assumption that a given input variable doesn't change (i.e., is frozen). I would like to do this by writing:

a_01 : (input1 == previous input1) with initial value true,

which is analogous to how this is done in AGREE (true -> (input1 = pre(input1))).

However, SpeAR doesn't allow me to write 'previous input1' without the initial value. To workaround this, I needed to create an extra state variable 'aux_input1' and write:

a_01 : input1 == previous input1 with initial value aux_input1

This is awkward and not at all intuitive to the user.

**Comment by lgwagner** [comment]
fixed in the grammar, will be included in RC8
