### ISSUE TITLE
Unit Checker

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#3]
Version SpeAR 2.2.2-alpha

The unit checker is not resolving that a scalar with the associated unit is an acceptable check. Not present in version 2.2.1-alpha

The error is shown in sensor.spear with assumption a_pla_ht and a_liq_ht

[ErrorEx.zip](https://github.com/lgwagner/SpeAR/files/119936/ErrorEx.zip)

**Comment by lgwagner** [comment]
This was an error caused by not providing a qualified name for imported units.

This was fixed by adding the code in SpearDeclarativeQualifiedNameProvider lines 18-20.
