### ISSUE TITLE
Check for Non-constant division when Z3 is not used.

### ISSUE THREAD

**Issue by lgwagner** [lgwagner/SpeAR#30]

**Comment by lgwagner** [comment]
fixed. Will allow nonlinearity for Z3 and YICES2 although YICES2 support for nonlinarity is very partial at the moment.

**Comment by agacek** [comment]
I think I was not clear in our conversation about this. JKind does not support non-linearity with Yices 2. There is some initial support for non-linearity in Yices 2, but not for the logic (QF_LIRA) that we use.
