### ISSUE TITLE
Equating Composite Type elements to a Specification call

### ISSUE THREAD

**Issue by lgwagner** [lgwagner/SpeAR#31]
![image](https://cloud.githubusercontent.com/assets/2699181/18335676/c993e5fa-7546-11e6-91d5-0a8b0cfcda36.png)

**Comment by lgwagner** [comment]
FYI this works:

![image](https://cloud.githubusercontent.com/assets/2699181/18335713/356d1bc0-7547-11e6-806d-5783f126c391.png)

**Comment by lgwagner** [comment]
The solution to this might be to auto-create macros for array/record indexes/field references, such that they do not appear in the file itself.

**Comment by manthonyaiello** [comment]
If you do auto-create macros, would they not appear in the CEX? This might actually be good, but might also surprise the user.
