### ISSUE TITLE
Feature request: Realizability analysis

### ISSUE THREAD

**Issue by jendavis** [lgwagner/SpeAR#37]
When requirements conflict some of the time but not all of the time, the requirements set will pass the consistency check in SpeAR. However, "occasionally conflicting" requirements implicitly constrain the input variables, which is not good and surprises the user. See the example below where requirements r1 and r2 conflict when the input a is equal to 3. Hence I can prove a property that a is never equal to 3, even though I have no such assumptions on the input a. Typically this implicit constraint on the input would be unbeknownst to the user. 

Realizability analysis is supported by AGREE and catches this kind of problem, providing a counterexample. I request that realizability analysis be added in the next major version of SpeAR. 

---

Specification test

Inputs:
a : int

Outputs:
b : int

Requirements:
r1: a==3 implies b==2
r2: a==3 implies b==3

Properties:
bad_prop: not (a==3)

**Comment by lgwagner** [comment]
This is not in a release, but has been implemented in the main branch. I will close this and you can reopen it after testing it.

**Comment by manthonyaiello** [comment]
@lgwagner — you didn't actually close this. Was that intentional?
