### ISSUE TITLE
Step Numbers Inconsistent Between the Eclipse and Excel Traces

### ISSUE THREAD

**Issue by AFRL-VVCAS** [lgwagner/SpeAR#39]
In eclipse the trace step number starts at 1 while in excel the trace starts at 0. This might confuse some users.

**Comment by manthonyaiello** [comment]
My cursory investigation suggests that this is a Jkind issue. Do we have some mechanism in place to link our issues to Jkind issues?

**Comment by lgwagner** [comment]
I can tell you that the JKind developers is receiving these emails. That is
one mechanism...

**Comment by lgwagner** [comment]
I'm going to close this for now and mark dontfix. It's a minor issue and will require some rework of the mechanism used to display both Excel and Eclipse.

**Comment by agacek** [comment]
I do get these emails, but sometimes there are many of them. Feel free to contact me directly or post on JKind github about anything important.

As for the numbering, it's a discrepancy in JKind which I'm hesitant to fix for backwards compatibility reasons. But you should be able to override the appropriate classes from JKind to change either one of the numberings to match what you want.
