### ISSUE TITLE
Counterexample Real Number Representation

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#46]
In current counterexample (CE) traces through Eclipse, the default view of real numbers is to leave it the number in fractional form. This is ideal for ensuring that rounding errors are not specified in the traces but can be distracting for user readability when the precision is not critical. 
- i.e. 1356283/25000 == 54.25132

If a trace with fractional form is displayed in a spreadsheet the fractional form is not maintained but is automatically converted to decimal form with rounding. This is also not ideal since the fractional information has been lost (if desired).

Suggestion:
- Add a setting in the Preferences dialog to display real values as fractional or decimal form.
  - If decimal form desired, allow the user to define a length of precision (if allowed by jKind)

**Comment by lgwagner** [comment]
Decimal format is all that is output by JKind right now. To support both we'd need some flag we can pass to JKind to get both, and that's not available.

I'm also not convinced there is a ton of value. I'm sure infinite precision is nice, but you would have to be getting counterexamples where you need precision out to the 7th or 8th (the actual number of digits of precision JKind provides is unknown to me) digit before JKind would hide that precision from you. I don't believe we're building or analyzing anything that complicated yet.

@agacek what is your take?

**Comment by agacek** [comment]
JKind has a certain default, but you should be able to override that if you want. Thus it is possible to support a flag to pick output format. That said, I've found fractions to rarely be useful. The approach we take in Excel is to truncate the values, but then add a cell comment with 100 digits of precision for those who want more.

**Comment by lgwagner** [comment]
Aaron, can you live with Andrew's suggested fix? I think if you use the excel output in the rare circumstances when high precision is needed you should be able to get the behavior you're looking for. I have no idea how to test it though. Do you have any examples?

**Comment by AFifarek** [comment]
First, I believe this came up with something Jon is trying to do with his work on his thesis using jKind. With that work, having the ability for jKind to output rational forms of a number would be critical.

As for use in SpeAR, it is likely that decimal (rather than rational) form is desired for counterexample traces. Rarely do most counterexamples need the rational to describe the steps being taken.

We may still want a menu option for allowing the user to define a certain decimal precision while Excel provides the "more complete" numerical representation.

I'll have to dig up an example that generates large rational counterexamples to test this on.

**Comment by lgwagner** [comment]
Implemented
