### ISSUE TITLE
Remove generated artifacts from the repository

### ISSUE THREAD

**Issue by manthonyaiello** [lgwagner/SpeAR#55]
Including the generated artifacts (from running Xtext's "generate language framework") means that whenever there is a change to the language, a large set of resources are marked as modified by git. This complicates identifying meaningful changes for atomic commits as well as changing branches. While there is some value in committing such artifacts, I contend that it is largely subsumed by the binary versions of the tool that are posted to github.

I suggest that all of the artifacts in any `src-gen`, `model/generated`, as well as any `plugin.xml_gen` be removed from the repository and then added to the `.gitignore` file.

**Comment by lgwagner** [comment]
We've had this argument internally over the years. Do generated XText artifacts belong in the repo? Some claim no, some claim yes, but there can be issues from XText version to version that can cause mild changes in the behavior. If you have the generated artifacts you don't need to rebuild the tool.

I could be swayed in either direction as I've never felt strongly one way or another. Might be good to ask @agacek his opinion on this.

**Comment by agacek** [comment]
My general view is that we should not check in any files that are generated by the build process. The problem is that currently the Xtext generated files are not generated as part of the build process. Thus I would lean towards checking them in. That way people do not need to remember to re-run Xtext each time they pull new code. As Lucas mentioned, this also helps smooth over issues with different versions of Xtext. 

In an ideal world our build process (which is basically just the Eclipse builder) would automatically run Xtext when the .xtext file changes.

**Comment by manthonyaiello** [comment]
@agacek: I understand your point: it is a bit bothersome to have to click on "generate language infrastructure" before rebuilding the tool. However, unless we check in the language infrastructure for each commit of each in-flight feature or bugfix branch, people testing those branches will have to remember to generate the language infrastructure as they move amongst branches for testing.

If we do check in the language infrastructure for feature / bugfix branches, I worry a bit about the eventual merge back to develop: it seems likely that all of the grammar changes will have to be first integrated and an integrated regeneration of the language infrastructure will have to be pushed to develop. That seems messy and error-prone.

Moreover, possibly because I generate the language artifacts on a Mac but Lucas commits the upstream versions using Windows, whenever I regenerate the language infrastructure, there are _hundreds_ of changed files. (This doesn't happen when I simply re-run generation on a fresh pull of master, so perhaps it's just that small changes cause big effects?)

For the most part, I think that we don't figure that our users will be building SpeAR — instead, we figure that our users will use the point releases that we post. If we _do_ think people will be building from code, we could, as a middle ground, commit the language infrastructure to master, but keep it out of develop and the various feature / bugfix branches. This inserts a step in releasing to master, of course, but it might give us the best of both worlds?

**Comment by lgwagner** [comment]
I'm ok removing the generated artifacts. We have a small number of people who are actually building things and it will greatly simplify the repository.

@manthonyaiello Do you mind doing this on a branch and issuing a merge request when you're done?

**Comment by manthonyaiello** [comment]
@lgwagner will do.

**Comment by lgwagner** [comment]
Fixed.
