### ISSUE TITLE
Alias record types

### ISSUE THREAD

**Issue by manthonyaiello** [lgwagner/SpeAR#57]
Record types _can_ be aliased in SpeAR, like this:
```
  record_t is a record {
    a: int,
    b: int
  }
  
  record_alias_t is a record_t
```

However, having done that, you can't actually _do_ anything with the alias:
```
  r1:
    record_ == record_alias
    
  r2:
    record_alias.b == 1
```

`r1` yields the error "Operator '==' not defined on units {a : scalar, b : scalar}, scalar" and `r2` yields the error "Couldn't resolve reference to FieldType 'b'."

Type aliasing for scalars in SpeAR works as expected, so type aliasing for record types should be supported.

Attached is a .txt file with SpeAR providing an example.
[type-alias.txt](https://github.com/lgwagner/SpeAR/files/666989/type-alias.txt)

**Comment by lgwagner** [comment]
This is actually more complicated than I had considered. Reopening it.

**Comment by lgwagner** [comment]
Closed this again. I added a validation that prevents units from being applied to aliases for composite types. The language does not allow you to represent a composite unit. Instead, we propgate the units of the underlying type.

I'm still not sure I like this completely, but it's better than what we had.
