### ISSUE TITLE
Translation NPE equating spec calls to record fields

### ISSUE THREAD

**Issue by manthonyaiello** [lgwagner/SpeAR#58]
When a record field access is equated to a spec call, a null-pointer exception is raised on translation. This happens whether the record field is a scalar or is itself a record.

The null pointer arises because the `FormalConstraintImpl` that is created has a null value for `expression`. This is first visible in `SSpecification.build` on line 49, but is obviously arising earlier in the parsing/translation process.

The three files attached will demonstrate the issue. Commented code is provided for exploring both scalar fields as well as record fields.

[called.txt](https://github.com/lgwagner/SpeAR/files/667288/called.txt)
[caller.txt](https://github.com/lgwagner/SpeAR/files/667289/caller.txt)
[types.txt](https://github.com/lgwagner/SpeAR/files/667290/types.txt)

**Comment by manthonyaiello** [comment]
This can be worked around by capturing the record-field access in a macro and then equating the macro to the spec call.

**Comment by lgwagner** [comment]
This is a duplicate of #31
