### ISSUE TITLE
Definition File Wizard Incorrect Dialog

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#6]
Tried out the new Wizard functionality in 2.4.0-alpha to create new Definitions or Specification files (File->New->Other)

**For the SpeAR Definitions section:**
SpeAR->Create a new SpeAR definitions file

Dialog:
_Title Header says:_ "SpeAR Specification The wizard creates a new SpeAR specification"
_What it should say:_ "SpeAR Definition The wizard creates a new SpeAR definition"

Also, is there a way to force the .spear extension in the wizard? I was able to successfully complete the wizard by wiping out the filename and not adding an extension. This prevented the xtext nature from being active on the file (as expected).

**Comment by lgwagner** [comment]
Fixed in commit 81644b394a40fbc68901b385fe672a24cc4642e4.
