### ISSUE TITLE
Scientific Notation Textual Highlighting

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#60]
When using scientific notation to define a number the text highlighting is not consistent throughout the number. This could be a limitation forced down by Xtext.

![image](https://cloud.githubusercontent.com/assets/6787980/21901475/e6a2054a-d8c5-11e6-8ad1-a9b305dd5776.png)

**Comment by lgwagner** [comment]
I've investigated this but I don't have the first clue on how to fix it and I'm not sure it's worth the budget at the moment.

**Comment by lgwagner** [comment]
Aaron,

Do you mind this format? Keep in mind that the way I've implemented this will require you to explicitly using the +/- sign on the exponent.

You can say 10.0E-1, 10.0e-1, 10.0e+1, or 10.0E+1 but not 10.0E1

**Comment by lgwagner** [comment]
@manthonyaiello

**Comment by AFifarek** [comment]
Seems fine to me.

**Comment by lgwagner** [comment]
Tony pointed out something: now 'e' is a keyword in the language. Not good. I'll have to figure something else out.

**Comment by AFifarek** [comment]
Oh good point ... I didn't think of that initially.

**Comment by agacek** [comment]
How does this look?

![image](https://cloud.githubusercontent.com/assets/172168/25751217/d8c3edfa-3179-11e7-8424-0b7eac696ed1.png)

**Comment by manthonyaiello** [comment]
Looks perfect, to me.

Tony

**Comment by AFifarek** [comment]
I'm happy with that.
