### ISSUE TITLE
Feature Request: Flag for IVC

### ISSUE THREAD

**Issue by jendavis** [lgwagner/SpeAR#61]
It would be helpful to have a checkbox to turn IVC cores on and off. When doing entailment, it's not necessary to compute the traceability results that IVC provides, and it seems to slow things down by about 30%.

**Comment by lgwagner** [comment]
![image](https://cloud.githubusercontent.com/assets/2699181/22132709/438095cc-de81-11e6-835e-113f15b13c92.png)
