### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by lgwagner** [lgwagner/SpeAR#70]
SpeAR needs a user guide.

@AFifarek please post the outline for the guide in here when you get some time.

**Comment by AFifarek** [comment]
# **SpeAR v2.0 Users Guide Outline**
_Last Updated: 2017-02-21_

1. Introduction (Jen, with input from Aaron)
    * Motivation for SpeAR
    * Overview of this user guide
    * Reference publications to date

2.  Installation Instructions (Aaron with support from Jon)

3. Developing a specification (Aaron with support from Jon)
    * Walk through building a simple example - "Hello, world"
      * EX: Add two variables, say they're greater than zero. Missing assumption that one is greater than zero. Try to use words that make sense—a real problem.
    * Sections of a specification and what they mean
    * Introduce basic grammar elements

4. Running an example and interpreting the results (Aaron with support from Jon)
    * Checking properties (Entailment)
       * How to tell which properties passed and which failed
       * How to view a counterexample
       * Make a change so that the previously failed property now passes
    * Consistency
    * Realizability
5. Building a more complex example (Aaron with support from Jon) 
    * Definitions file
    * Calling another spec from a spec (composition)
    * Introduce additional useful grammar elements
6. Advanced Techniques (Lucas)
    * Creating and using user-defined patterns
        * Simple example with a pattern—maybe absolute value pattern
        * Bounded existence example (For tanks: &quot;If water level gets above top height sensor, then within 3 time steps it will be below that top height sensor level.&quot;)
    * Pattern validation
    * (Debated) Lemmas (for use when analysis finds no counterexamples but doesn't prove it). A property to help prove a property.
7. Software Engineering Process Inclusion (Jen with support from others)
    * (Jen) Attributes (source, trace, etc.). Include a table with these.
    * (Jen with support from Janet) Export to Excel
    * (Lucas) Traceability
8. Appendix A: Complete grammar description (Jen)
    * List all grammar elements (use demo file?)
    * Finer points of grammar--interpretation and meaning
       * no else defaults to true
       * binding in "prev x with initial value y" 0&quot; ("with initial value" binds tighter than ">")
       * limitations and advice on spec calls (not allowed in macro, can be used as Boolean (a==spec(b)) in a more complex expression)
          * Maybe: (mode==X) implies |r,s| == spec specB(e,f)
     * Advanced grammar elements (O, H, etc.)--not intended for the average user and not necessary
9. Appendix B: Analysis Techniques (Lucas)
    * Introduce JKind, give a reference to read more
    * Entailment
    * Consistency (Keep, drop, or turn into example generator?)
        * Checks up to 8 steps by default. Configurable in Preferences (Depth of Consistency)
    * Realizability
    * Traceability
10. Appendix C: Configuration of SpeAR Preferences (Lucas) 
      * Configuration of Analysis
           * Toggling generation of Lustre files
           * Depth of logical consistency checking
      * More

Reference bug list on website.

**Comment by lgwagner** [comment]
Implemented
