### ISSUE TITLE
Decimal Inconsistencies

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#9]
In the attached file (after_before.spear) there is a set of assumptions to increment a real number value by some const value. Once the value exceeds the max the system will signal that the value was exceeded and then set the output to the max of the range. In order to verify the behavior, 2 counter-examples (CEs) were implemented with the anticipation that they would both fail (r_CE_01 and r_CE_02).

Tests (Changing assumptions)
- a01a and a02a active: 
The CE that an over-sig can not occur (r_CE_01) should be proven wrong by continuely recieving positive input within the range of (0.0 <= in_value <= 0.2). 

- a01a and a02b active: 
The CE that an over-sig can not occur (r_CE_01) is proven wrong by continuely recieving positive input within the range of (0.0 <= in_value <= 1.0). The trace demonstartes the summation over steps is property maintained and results as expected.

- a01a and a02c active:
The CE that an over-sig can not occur (r_CE_01) is proven wrong by continuely recieving positive input within the range of (0.0 <= in_value <= 1.2). The trace demonstrates the summation properly (as in the previous case).

It was thought that there is a possible truncation in the real numbers that was causing and issue (0.2 becoming 0.0 internally). Therefore dec_bug.spear (also attaached) was created to test this behavior. This did not demonstrate the issue and therefore may help to narrow the possible error locations.

[SpeAR_Files.zip](https://github.com/lgwagner/SpeAR/files/219331/SpeAR_Files.zip)

**Comment by lgwagner** [comment]
This appears to be the result of a bug in Z3 4.4.1. 

We are submitting a bug report to them. Possible workarounds are to use SMT Interpol (or any other solver you have installed) or downgrade to Z3 4.3.2. (potentially 4.4.0 does not exhibit the issue, we have not checked.)
