### ISSUE TITLE
Test commandline

### ISSUE THREAD

**Issue by lgwagner** [lgwagner/SpeAR#93]
We need to thoroughly test the commandline before our next release. Dan, did you test it?

**Comment by jendavis** [comment]
I agree. I think the first step is to document how to run it. A page or two with simple instructions and a couple of screenshots would work to document this and batch processing. That documentation can eventually be added to the Wiki.

**Comment by lgwagner** [comment]
I just ran it on a few elements. I'm not saying it was thoroughly tested, but it's good enough to release.
