### ISSUE TITLE
Observer flags for middle section

### ISSUE THREAD

**Issue by lgwagner** [lgwagner/SpeAR#95]
It would be nice if you could generate tests for each requirement. However there are some tricky things, such as handling implication.

If you have a requirement A implies B you don't want to simply negate that. What you really want is to see a trace where both A and B are true. I need to do some thinking if this is the only change to make.

**Comment by jendavis** [comment]
I don't understand why the same rules wouldn't apply. Maybe we can discuss this.

**Comment by lgwagner** [comment]
Tabling this for now.
